export interface UIObject {
    _internalElementName: string
    elementCaption: string
    elementName: string
    elementID: string
    ourCode: string
    ourCode2: string
    elementType: string
    defaultAccessPath: string
    defaultValue: string
    isServerFiltering: boolean
    mapName: string
    mapKey: string
    collectionName: string
    onClickAction: string
    elementKey: number
    parentKey: number
    width: number
    objectTypeKey: number
    referenceElementKey: number
    isVisible: boolean
    isTabVisible: boolean
    isMobVisible: boolean
    isMust: boolean
    isReadOnly: boolean
    isFreeze: boolean
    isEnable: boolean
    isAllowEdit: boolean
    children: UIObject[]
    cssClass: string
    validationMessage: string
    parentCssClass: string
    uiSection: string
    urlAction: string
    urlController: string
    iconCss: string
    toolTip: string
    dataType: string
    enterKeyAction: string
    format: string
    readController: string
    readAction: string
    createController: string
    createAction: string
    updateController: string
    updateAction: string
    deleteController: string
    deleteAction: string
    xs: number
    sm: number
    md: number
    lg: number
    xlg: number
    isCd01: number
    isCd02: number
    isCd03: number
    isCd04: number
    isCd05: number
    isCd06: number
    isCd07: number
    isCd08: number
    isCd09: number
    isCd10: number
    isCd40: number
    isCd102: number
    isCd150: number
    reportName: string
    reportPath: string
    nextObjKy: number
    nextObjName: string
    nextObjType: string
    onBeforeComboLoad: string
    onAfterComboLoad: string
    isMustElements: string[]
}

